name: cubox-i
version: 18-0.1
summary: i.Mx6 cubox-i gadget
description: |
 Bootloader files and partitoning data to create a
 bootable Ubuntu Core 18 image for the cubox-i.
type: gadget
base: core18
architectures:
  - build-on: amd64
    run-on: armhf
confinement: strict
grade: stable

parts:
  uboot:
    source: https://gitlab.denx.de/u-boot/u-boot.git
    source-branch: v2019.04
    source-depth: 1
    plugin: nil
    override-build: |
      # Apply our uboot patch
      git apply -v ../../../uboot.patch

      make mx6cuboxi_defconfig
      CROSS_COMPILE=arm-linux-gnueabihf- make

      cp u-boot.img $SNAPCRAFT_PART_INSTALL/u-boot.img
      cp SPL $SNAPCRAFT_PART_INSTALL/cubox-i-spl.bin

      mkdir $SNAPCRAFT_PART_INSTALL/boot-assets

      tools/mkenvimage -r -s 131072 -o $SNAPCRAFT_PART_INSTALL/uboot.env ../../../uboot.env.in
      cd $SNAPCRAFT_PART_INSTALL
      ln -s uboot.env uboot.conf
    build-packages:
      - bc
      - bison
      - build-essential
      - device-tree-compiler
      - flex
      - libpython2.7-dev
      - python-minimal
      - on amd64:
        - gcc-arm-linux-gnueabihf

slots:
  i2c-1:
    interface: i2c
    path: /dev/i2c-1
  i2c-2:
    interface: i2c
    path: /dev/i2c-2
